name: Deploy Frontend Indiezone

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Gerar Build (Vite)
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Copiar arquivos para a VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
        # Auth
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PASSWORD }}
          source: "dist/*"
          target: "/var/www/indiezone/"
          strip_components: 1
